config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  STARS = [0, 1, 2, 3, 4, 5]
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: STARS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- app/views/layouts/application.html.erb -->
<head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for restaurant do |f| -%>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.submit class: "btn btn-primary" %>
<% end -%>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>All Restaurants</h1>
      <%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>
    </div>
  </div>
  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
        <ul>
          <li><%= restaurant.category %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<ul>
  <li>Address:<%= @restaurant.address %></li>
  <li>Phone number:<%= @restaurant.phone_number %></li>
  <li>Category:<%= @restaurant.category %></li>
  <ul>
    <% @reviews.each do |review| %>
  <li>Review:<%= review.content %> Rating:<%= review.rating %></li>
  <% end %>
  </ul>

<%= link_to "Add a review", new_restaurant_review_path(@restaurant) %>
<%= link_to " < back to list", restaurants_path %>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| -%>
  <%= f.input :content %>
  <%= f.input :rating, collection: Review::STARS %>
  <%= f.submit class: "btn btn-primary" %>
<% end -%>

app/views/reviews/new.html.erb
<%= render "form", review: @review %>